### ISSUE TITLE
FR: Afspil/Cast lydbøger til media player

### ISSUE THREAD

**Issue by JBoye** [TermeHansen/Bibliotek_dk#8]
Det ville være fantastisk at kunne bruge eReolen lydbøger som en media source, der kan caste til feks Sonos højtalere.

Min egen research indtil videre:

**https://pubhub-openplatform.dbc.dk/v1/user/loans**
Alle loans har et "orderId" som er et GUID. Det guid kan kopieres til denne url:

`https://audio.api.streaming.pubhub.dk/v1/stream/hls/*GUID*/playlist.m3u8`

Denne url kan åbnes direkte i VLC Player > "Åbn netværk" 

Alternativ kopier den ind på https://www.hlsplayer.org/ og tryk play

Den _burde_ man også kunne afspille direkte via HA, men det ser ikke ud til at virke på mine sonos højtalere. Jeg gætter på at det er pga krypteringen
```
action: media_player.play_media
data:
  media_content_id: hls-radio://https://audio.api.streaming.pubhub.dk/v1/stream/hls/*GUID*/playlist.m3u8
  media_content_type: music
target:
  entity_id: media_player.tv
```

**Comment by JBoye** [comment]
Konverter til mp3 med https://github.com/ytdl-org/youtube-dl

`youtube-dl https://audio.api.streaming.pubhub.dk/v1/stream/hls/*GUID*/playlist.m3u8 -x`

**Comment by JBoye** [comment]
Der er åbenbart allerede en youtube-dl wrapper indbygget i HA - https://www.home-assistant.io/integrations/media_extractor/

Så muligvis

```
action: media_extractor.extract_media_url
data: 
  url: https://audio.api.streaming.pubhub.dk/v1/stream/hls/*GUID*/playlist.m3u8
  format_query: bestaudio[ext=m4a]
```

Jeg har dog ikke mulighed for at teste det nu
